<a href="https://colab.research.google.com/github/mehmetcolgecen/TensorFlow/blob/main/1_Tensor_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [51]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [ ]:
#No need for now might be useful in future
#physical_devices = tf.config.list_physical_devices('GPU')
#tf.config.experimental.set_memory_growth(physical_devices[0], True)

# **Initialization Methods**

In [3]:
x = tf.constant(4)
x

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [4]:
#dtype argument can be "float" or "tf.float32"
x = tf.constant(4, shape=(1,1), dtype = tf.float32)
x

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[4.]], dtype=float32)>

In [5]:
x = tf.constant ([1,2,3])
x

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [10]:
arr = np.array([[1,2,3],[4,5,6]])
x = tf.constant(arr)
x

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [12]:
#converts pandas data frame into numpy array
df = pd.DataFrame(arr)
x=tf.constant(df)
x

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [13]:
x = tf.ones((3,3))
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [15]:
x=tf.zeros((2,3))
x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [20]:
x=tf.eye((3))
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [22]:
#randomly initialize with standart distibition
x = tf.random.normal((3,3))
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.405853  , -0.10078445,  0.45303673],
       [-0.4296344 , -1.9473711 , -1.0242529 ],
       [-1.3283232 , -0.66924334, -1.233518  ]], dtype=float32)>

In [23]:
#randomly initialize with uniform distibition
tf.random.uniform((3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.66010857, 0.2679788 , 0.27205884],
       [0.49216092, 0.7835747 , 0.88348377],
       [0.9793452 , 0.7915299 , 0.51161873]], dtype=float32)>

In [26]:
x = tf.range(1,10,2)
x

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 3, 5, 7, 9], dtype=int32)>

In [28]:
#veri tipini değiştirelim
tf.cast(x, dtype=tf.float64)

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([1., 3., 5., 7., 9.])>

# **Mathematical Operations**

In [30]:
x = tf.constant([1,2,3])
y = tf.constant([9,8,7])

In [31]:
#elementwise add
tf.add(x,y) # same with x + y

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 10, 10], dtype=int32)>

In [33]:
#elementwise
tf.subtract(y,x) # same with y-x

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([8, 6, 4], dtype=int32)>

In [34]:
#element wise
tf.divide(x,y) # same with x/y

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.11111111, 0.25      , 0.42857143])>

In [36]:
#elementwise
tf.multiply(x,y) # same with x*y

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 9, 16, 21], dtype=int32)>

In [42]:
#dotproduct ==> elementwise multiplication and summation
tf.tensordot(x, y, axes=1)

<tf.Tensor: shape=(), dtype=int32, numpy=46>

In [44]:
#mathematically;
1*9 + 2*8 + 3*7

46

In [48]:
#in order to sum raws and columns
tf.reduce_sum(x,axis=0)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [50]:
#you can produce dot product using this one like:
tf.reduce_sum(x*y, axis=0)

<tf.Tensor: shape=(), dtype=int32, numpy=46>

In [55]:
#Matrix multiplication
x=tf.random.normal((2,3))
y=tf.random.normal((3,4))
tf.matmul(x,y) #same with x @ y

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 0.9636002 , -3.8877296 , -0.607612  , -1.9823567 ],
       [ 3.283511  ,  0.09548222,  0.19016755, -0.5522427 ]],
      dtype=float32)>

# Indexing and Reshaping

In [56]:
x =  tf.constant([1,2,3,4,5,6,7])
indices = tf.constant([0,5])
tf.gather(x, indices=indices)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 6], dtype=int32)>

In [58]:
x = tf.range(9)
x

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [59]:
x = tf.reshape(x, (3,3))
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)>

In [61]:
tf.transpose(x)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]], dtype=int32)>

In [64]:
tf.transpose(x, perm=[1,0]) #same result

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]], dtype=int32)>